# KEYS

bind = CTRL, SPACE, Launch apps, exec, walker -p "Start…"
bind = CTRL SHIFT, SPACE, Omarchy menu, exec, omarchy-menu
bind = SUPER SHIFT, S, Screenshot of region, exec, omarchy-cmd-screenshot
bind = CTRL SUPER SHIFT, S, Screen record a region, exec, omarchy-cmd-screenrecord region
bind = SUPER SHIFT, C, Color picker, exec, pkill hyprpicker || hyprpicker -a
bind = CTRL SUPER, V, exec, alacritty --title "clipse" -e clipse
bind=SHIFT SUPER,F,fullscreen

# INPUT

# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_layout = us
  kb_options = compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35
force_no_accel = true
  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Scroll faster in the terminal
windowrule = scrolltouchpad 1.5, tag:terminal

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
gesture = 3, horizontal, workspace

# MISC

# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
}
animation = workspaces, 1, 8, default


windowrulev2 = float,  initialTitle:clipse, class: Alacritty
windowrulev2 = center, initialTitle:clipse, class: Alacritty 
windowrulev2 = size 800 600, initialTitle:clipse, class: Alacritty 

# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_layout = us
  kb_options = compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35
force_no_accel = true
  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Scroll faster in the terminal
windowrule = scrolltouchpad 1.5, tag:terminal

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
gesture = 3, horizontal, workspace
